export const theme = {
    colors: {
        primary: '#003D29',
        primary2: '#7AB92D',
        secondary: '#898A8D',
        lightGrey: '#EBEBEB',
        darkGrey: '#5E5E60',
        black: '#000000',
        white: '#FFFFFF',
        grey: 'rgba(0, 0, 0, 0.25)',
        gold: '#F6A355',
        darkRed: '#601124',
    },
    fontFamily: {
        extralight: "PoppinsExtraLight",
        light: "PoppinsLight",
        regular: "PoppinsRegular",
        medium: "PoppinsMedium",
        semibold: "PoppinsSemiBold",
        bold: "PoppinsBold",
        extrabold: "PoppinsExtraBold",
        black: "PoppinsBlack",
        thin: "PoppinsThin",
    },
    fontSizes: {
        heading: 32,
        subheading: 24,
        body: 18,
        caption: 12,
        button: 16,
        label: 14,
        xxsmall: 8,
        xsmall: 10,
        small: 12,
        medium: 16,
        large: 20,
        xlarge: 24,
        xxlarge: 32,
    },
}
