import { Platform, StyleSheet } from "react-native";

export const storeProfileScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  image_background: {
    width: "100%",
    height: 200,
    position: "relative",
    zIndex: 3,
    backgroundColor: "#fff",
    marginBottom: 40,
  },
  close_button: {
    backgroundColor: "white",
    width: 35,
    height: 35,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 15,
    marginTop: 10,
    button: {
      backgroundColor: "white",
      width: 40,
      height: 40,
      borderRadius: 20,
      justifyContent: "center",
      alignItems: "center",
      shadow: {
        borderRadius: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        overflow: Platform.OS === "android" ? "hidden" : "visible",
      },
    },
  },
  store_image: {
    width: 75,
    height: 75,
    borderRadius: 10,
    position: "absolute",
    bottom: "-15%",
    left: 15,
    zIndex: 5,
  },
  button: {
    backgroundColor: "#204B38",
    borderRadius: 20,
    maxWidth: "30%",
    padding: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 30,
  },
  title: {
    fontSize: 20,
    fontFamily: "PoppinsSemiBold",
  },
  subtitle: {
    fontSize: 12,
    color: "#979797",
    fontFamily: "PoppinsRegular",
    marginBottom: 10,
  },
  link_container: {
    marginBottom: 10,
  },
  link: {
    display: "flex",
    justifyContent: "space-between",
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  link_left: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  icon: {
    backgroundColor: "#f6f6f6",
    padding: 5,
    borderRadius: 20,
    aspectRatio: 1.65 / 1,
    width: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  link_text: {
    color: "#292D32",
    fontFamily: "PoppinsRegular",
    fontSize: 13.5,
    letterSpacing: 0.2,
  },
});
